- name: My first play
  hosts: sandbox 
  connection: ssh
  gather_facts: true
 
  tasks:
    - name: Create a file
      tmsh:
          dest: "/tmp/test.txt"
          content: "This is some content"
